apiVersion: apps/v1
kind: Deployment
metadata:
  name: picweb
  namespace: pic
  labels:
    cattle.io/creator: norman
    app: picweb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: picweb
  template:
    metadata:
      labels:
        app: picweb
    spec:
      containers:
        - name: picweb
          image: imagekeyword
          ports:
            - name: tcp01
              containerPort: 4200
              protocol: TCP
          resources:
            limits:
              cpu: "1" 
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always
          securityContext:
            capabilities: {}
            privileged: false
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          stdin: true
          tty: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
      dnsConfig: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


